import type { UKDesignTheme } from "../theme.ts";

const baselineTheme: UKDesignTheme = {
  ref: {
    typeface: {
      plain: () => "Roboto",
      brand: () => "Roboto",
      emphasized: {
        plain: () => "Roboto Flex",
        brand: () => "Roboto Flex",
      },
      "weight-bold": () => "700",
      "weight-medium": () => "500",
      "weight-regular": () => "400",
    },
  },
  sys: {
    color: {
      lightMode: {
        "surface-tint": "103, 80, 164",
        "surface-tint-color": "103, 80, 164",
        "on-error-container": "#410e0bff",
        "on-error": "#ffffffff",
        "error-container": "#f9dedcff",
        "on-tertiary-container": "#31111dff",
        "on-tertiary": "#ffffffff",
        "tertiary-container": "#ffd8e4ff",
        tertiary: "#7d5260ff",
        shadow: "#000000",
        error: "#b3261eff",
        outline: "#79747E",
        "outline-variant": "#CAC4D0",
        "on-background": "#1D1B20",
        background: "#FFFBFF",
        "inverse-on-surface": "#F5EFF7",
        "inverse-surface": "#322F35",
        "on-surface-variant": "#49454F",
        "on-surface": "#1D1B20",
        "surface-variant": "#E7E0EC",
        surface: "#FFFBFF",
        "surface-container": "#F3EDF7",
        "surface-container-low": "#F5EFF7",
        "surface-container-lowest": "#F5EFF7",
        "surface-container-high": "#E6E0E9",
        "surface-container-highest": "#E6E0E9",
        "on-secondary-container": "#1d192bff",
        "on-secondary": "#ffffffff",
        "secondary-container": "#e8def8ff",
        secondary: "#625b71ff",
        "inverse-primary": "#d0bcffff",
        "on-primary-container": "#21005dff",
        "on-primary": "#ffffffff",
        "primary-container": "#eaddffff",
        primary: "#6750a4ff",
      },
      darkMode: {
        "surface-tint": "208, 188, 255",
        "surface-tint-color": "208, 188, 255",
        "on-error-container": "#f2b8b5ff",
        "on-error": "#601410ff",
        "error-container": "#8c1d18ff",
        "on-tertiary-container": "#ffd8e4ff",
        "on-tertiary": "#492532ff",
        "tertiary-container": "#633b48ff",
        tertiary: "#efb8c8ff",
        shadow: "#000000",
        error: "#f2b8b5ff",
        outline: "#938F99",
        "outline-variant": "#49454F",
        "on-background": "#E6E0E9",
        background: "#141218",
        "inverse-on-surface": "#322F35",
        "inverse-surface": "#E6E0E9",
        "on-surface-variant": "#CAC4D0",
        "on-surface": "#E6E0E9",
        "surface-variant": "#49454F",
        surface: "#1D1B20",
        "surface-container": "#211F26",
        "surface-container-low": "#1D1B20",
        "surface-container-lowest": "#1D1B20",
        "surface-container-high": "#36343B",
        "surface-container-highest": "#36343B",
        "on-secondary-container": "#e8def8ff",
        "on-secondary": "#332d41ff",
        "secondary-container": "#4a4458ff",
        secondary: "#ccc2dcff",
        "inverse-primary": "#6750a4ff",
        "on-primary-container": "#eaddffff",
        "on-primary": "#381e72ff",
        "primary-container": "#4f378bff",
        primary: "#d0bcffff",
      },
    },
  },
};

export { baselineTheme };
