import type { UKDesignTokens } from "./tokens.ts";

export interface UKDesignTheme {
  ref: UKDesignTokens["raw"]["ref"];
  sys: {
    color: {
      lightMode: {
        "surface-tint": string;
        "surface-tint-color": string;
        "on-error-container": string;
        "on-error": string;
        "error-container": string;
        "on-tertiary-container": string;
        "on-tertiary": string;
        "tertiary-container": string;
        tertiary: string;
        shadow: string;
        error: string;
        outline: string;
        "outline-variant": string;
        "on-background": string;
        background: string;
        "inverse-on-surface": string;
        "inverse-surface": string;
        "on-surface-variant": string;
        "on-surface": string;
        "surface-variant": string;
        surface: string;
        "surface-container": string;
        "surface-container-low": string;
        "surface-container-lowest": string;
        "surface-container-high": string;
        "surface-container-highest": string;
        "on-secondary-container": string;
        "on-secondary": string;
        "secondary-container": string;
        secondary: string;
        "inverse-primary": string;
        "on-primary-container": string;
        "on-primary": string;
        "primary-container": string;
        primary: string;
      };
      darkMode: {
        "surface-tint": string;
        "surface-tint-color": string;
        "on-error-container": string;
        "on-error": string;
        "error-container": string;
        "on-tertiary-container": string;
        "on-tertiary": string;
        "tertiary-container": string;
        tertiary: string;
        shadow: string;
        error: string;
        outline: string;
        "outline-variant": string;
        "on-background": string;
        background: string;
        "inverse-on-surface": string;
        "inverse-surface": string;
        "on-surface-variant": string;
        "on-surface": string;
        "surface-variant": string;
        surface: string;
        "surface-container": string;
        "surface-container-low": string;
        "surface-container-lowest": string;
        "surface-container-high": string;
        "surface-container-highest": string;
        "on-secondary-container": string;
        "on-secondary": string;
        "secondary-container": string;
        secondary: string;
        "inverse-primary": string;
        "on-primary-container": string;
        "on-primary": string;
        "primary-container": string;
        primary: string;
      };
    };
  };
}
